# Assignment 1: Data Profiling (EDA) Report

## Student Depression Dataset

### Group Members

1. Name: NUREEN ADREANA BINTI MOHD KHAIRI
   Matric Number: A213743

2. Name: NAJWA HANNAH BINTI NORSAIDI
   Matric Number: A209494

3. Name: MIMI NAZIRA BINTI MAZLAN
   Matric Number: A209431

4. Name: NUR ALEEYA BINTI KAMARUDIN
   Matric Number: A209786

Course: TTTC3213
Assignment 1: Data Profiling (EDA) Report

## 1. Scenario

Student depression is an important issue in higher education, as students may experience different academic, financial, social and personal challenges. This dataset contains information about students' backgrounds, academic performance, financial conditions, health conditions and depression status. This analysis aims to identify data quality issues, investigate unusual values and assess whether the dataset is suitable for studying factors associated with student depression.

### Questions to Investigate

1. Are there missing, duplicated or invalid values in the dataset?
2. Are there unusual values or outliers in numerical attributes?
3. Are there any privacy and bias risks when using student-related information?

## 2. Data Source

Dataset Name: Student Depression Dataset

File Format: Excel (.xlsx)

Number of Records: 4,464

Number of Attributes: 13

Original Dataset URL: [https://www.kaggle.com/datasets/hopesb/student-depression-dataset]

The dataset was obtained by downloading the Excel file and importing it into Python using the Pandas library.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel(
    "../../data/Student_Depression_Dataset.xlsx"
)

df.head()

,Gender,Age,Family_background,Relationship_status,Marital_status,Living_style,Current_semester,CGPA,friend_circle,Health_condition,Cost_without_study,Home_division,Depression
0,Female,22,Middle class,Single,Unmarried,Bachelor,8,3.43,Yes,Critical,10113,Chittagong,Yes
1,Male,19,Middle class,Single,Unmarried,Bachelor,2,3.70,Yes,Abnormal,13815,Chittagong,Yes
2,Male,23,Middle class,Single,Unmarried,Family,8,3.28,No,Abnormal,15450,Dhaka,Yes
3,Male,20,Middle class,Complicated,Unmarried,Family,2,3.77,No,Good,17413,Dhaka,No
4,Female,21,Middle class,Single,Unmarried,Family,1,4.00,No,Abnormal,16693,Dhaka,Yes

In [3]:
# Display dataset dimensions
print("Number of rows and columns:", df.shape)

# Display first five records
display(df.head())

# Display last five records
display(df.tail())

# Display column names
print("\nColumn Names:")
print(df.columns.tolist())

# Display dataset information
df.info()

# Display statistical summary
display(df.describe())

Number of rows and columns: (4464, 13)

,Gender,Age,Family_background,Relationship_status,Marital_status,Living_style,Current_semester,CGPA,friend_circle,Health_condition,Cost_without_study,Home_division,Depression
0,Female,22,Middle class,Single,Unmarried,Bachelor,8,3.43,Yes,Critical,10113,Chittagong,Yes
1,Male,19,Middle class,Single,Unmarried,Bachelor,2,3.70,Yes,Abnormal,13815,Chittagong,Yes
2,Male,23,Middle class,Single,Unmarried,Family,8,3.28,No,Abnormal,15450,Dhaka,Yes
3,Male,20,Middle class,Complicated,Unmarried,Family,2,3.77,No,Good,17413,Dhaka,No
4,Female,21,Middle class,Single,Unmarried,Family,1,4.00,No,Abnormal,16693,Dhaka,Yes

,Gender,Age,Family_background,Relationship_status,Marital_status,Living_style,Current_semester,CGPA,friend_circle,Health_condition,Cost_without_study,Home_division,Depression
4459,Female,26,Middle class,In a Relationship,Separated,Family,11,2.97,No,Critical,12619,Khulna,Yes
4460,Male,28,Lower Middle class,Single,Unmarried,Family,8,2.60,No,Normal,2806,Rajshahi,Yes
4461,Female,23,Middle class,In a Relationship,Married,Bachelor,10,2.80,No,Good,14066,Rajshahi,No
4462,Female,23,Middle class,Complicated,Married,Family,5,3.00,Yes,Normal,14338,Barisal,No
4463,Female,21,Lower Middle class,Single,Unmarried,Family,5,2.56,Yes,Abnormal,4000,Barisal,Yes

Column Names:
['Gender', 'Age', 'Family_background', 'Relationship_status', 'Marital_status', 'Living_style', 'Current_semester', 'CGPA', 'friend_circle', 'Health_condition', 'Cost_without_study', 'Home_division', 'Depression']
<class 'pandas.DataFrame'>
RangeIndex: 4464 entries, 0 to 4463
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Gender               4464 non-null   str
 1   Age                  4464 non-null   int64
 2   Family_background    4464 non-null   str
 3   Relationship_status  4464 non-null   str
 4   Marital_status       4464 non-null   str
 5   Living_style         4464 non-null   str
 6   Current_semester     4464 non-null   int64
 7   CGPA                 4464 non-null   float64
 8   friend_circle        4464 non-null   str
 9   Health_condition     4464 non-null   str
 10  Cost_without_study   4464 non-null   int64
 11  Home_division        4464 non-null   str
 12  Depression           4464 non-null   str
dtypes: float64(1), int64(3), str(9)
memory usage: 453.5 KB

               Age  Current_semester         CGPA  Cost_without_study
count  4464.000000       4464.000000  4464.000000         4464.000000
mean     22.619176          5.401210     3.412753        11242.978271
std       2.022980          2.578476     0.385605         6640.144019
min      17.000000          0.000000     2.250000            0.000000
25%      21.000000          3.000000     3.150000         6100.000000
50%      23.000000          5.000000     3.490000         9500.000000
75%      24.000000          7.000000     3.700000        15439.000000
max      28.000000         13.000000     4.000000        32000.000000

### Initial Dataset Overview

The dataset contains 4,464 student records and 13 attributes.

The attributes include demographic information, academic performance, financial conditions, social background, health conditions and depression status.

The dataset consists of both numerical and categorical variables, making it suitable for examining different types of data quality issues.